#!/usr/bin/env python3

import compare

def main():
    import sys

    if len(sys.argv) != 3:
        print("usage: %s old new" % sys.argv[0])
        sys.exit(2)

    compare.files(sys.argv[1], sys.argv[2])

if __name__ == "__main__":
    main()
